--dünyanýn toplam nufusü, toplam vaka sayýsý ve toplam ölüm sayýsý,

SELECT SUM(POPULATION_)AS DÜNYADAKÝ_TOPLAM_NUFÜS,  
SUM(TOTAL_CASES)AS DÜNYADAKÝ_TOPLAM_VAKA, ROUND(SUM(TOTAL_CASES)*100/SUM(POPULATION_),2) AS DÜNYADA_VAKA,
SUM(TOTAL_DEATHS) AS DÜNYADAKÝ_TOPLAM_ÖLÜM, ROUND(SUM(TOTAL_DEATHS)*100/SUM(POPULATION_),2)AS DÜNYADA_ORAN
FROM CASES_BY_COUNTRIES
WHERE 1=1
AND DATE_='06.01.2021'