--11.el yýkama tesisleri olan ülkelerin ORTALAMA toplam vaka verileri
SELECT COU.COUNTRYID, COUNTRYNAME,HANDWASHING_FACILITIES, AVG(TOTAL_CASES)  FROM CASES_BY_COUNTRIES CBC 
INNER JOIN COUNTRY COU ON COU.COUNTRYID=CBC.COUNTRY_ID
WHERE HANDWASHING_FACILITIES IS NOT NULL
GROUP BY COUNTRYNAME
ORDER BY COU.COUNTRYID