--asya kýtasýndaki ülkelerin 2020 ocak ayý içindeki TOTAL_DEATHS_PER_MILLION ve  TOTAL_CASES_PER_MILLION oranlarýný getirin
SELECT CONTINENTNAME,countryname,date_, TOTAL_DEATHS_PER_MILLION, TOTAL_CASES_PER_MILLION
FROM CASES_BY_COUNTRIES CBC 
INNER JOIN COUNTRY COU ON COU.COUNTRYID=CBC.COUNTRY_ID
INNER JOIN CONTINENT CONT ON CONT.ID=COU.CONTINENTID
WHERE 1=1
AND CONTINENTNAME='Asia' 
AND DATE_ BETWEEN '01.01.2020' AND '31.01.2020'
ORDER BY CBC.ID