--yoksulluk durumuna göre NUFUS ve toplam vaka oranýný bulun.

SELECT COUNTRYID, COUNTRYNAME, POPULATION_, EXTREME_POVERTY, TOTAL_CASES_PER_MILLION FROM CASES_BY_COUNTRIES CBC
INNER JOIN COUNTRY COU ON COU.COUNTRYID=CBC.COUNTRY_ID
WHERE EXTREME_POVERTY IS NOT NULL
GROUP BY COUNTRYNAME
ORDER BY COUNTRYID