--afrika kýtasý ülkelerinin toplam nüfüsü ve toplam vakalarýný ve AVRUPA kýtasýnýn top UNÝON ÝLE BÝRLEÞTÝR
SELECT COUNTRYNAME, POPULATION_,TOTAL_CASES  FROM CASES_BY_COUNTRIES CBC 
INNER JOIN COUNTRY COU ON COU.COUNTRYID=CBC.COUNTRY_ID
INNER JOIN CONTINENT CONT ON CONT.ID=COU.CONTINENTID
WHERE 1=1
AND CONTINENTNAME='Africa'
AND DATE_='06.01.2020'

UNION 

SELECT COUNTRYNAME, POPULATION_,TOTAL_CASES  FROM CASES_BY_COUNTRIES CBC 
INNER JOIN COUNTRY COU ON COU.COUNTRYID=CBC.COUNTRY_ID
INNER JOIN CONTINENT CONT ON CONT.ID=COU.CONTINENTID
WHERE 1=1
AND CONTINENTNAME='Europe'
AND DATE_='06.01.2021'