--gsmh ya göre TOPLAM VAKA DURUMUNU KIYASLA

SELECT DISTINCT(COUNTRYNAME), GDP_PER_CAPITA, SUM(TOTAL_CASES) FROM CONTINENT CO 
INNER JOIN COUNTRY COU            ON COU.CONTINENTID=CO.ID 
INNER JOIN CASES_BY_COUNTRIES CBC ON CBC.COUNTRY_ID=COU.COUNTRYID
GROUP BY COUNTRYNAME, GDP_PER_CAPITA
ORDER BY GDP_PER_CAPITA DESC