--5.aþýya  baþlayan ülkenin toplam vaka, toplam ölüm, toplam test, yoðun bakým hasta oraný 
--nüfüs yoðunluðunu ve positif oranlarýný bulun

SELECT COUNTRYID, COUNTRYNAME, DATE_,TOTAL_VACCINATIONS, NEW_VACCINATIONS, 
TOTAL_CASES,TOTAL_DEATHS, TOTAL_TESTS, ICU_PATIENTS_PER_MILLION  
FROM CASES_BY_COUNTRIES CBC
INNER JOIN COUNTRY COU ON COU.COUNTRYID=CBC.COUNTRY_ID
WHERE  NEW_VACCINATIONS IS NOT NULL 