--1.verilen tarihe göre kýtalardaki toplam ölüm ve toplam vaka bilgisini getiren sorguyu yaz.
CREATE OR REPLACE PROCEDURE TARIHE_GORE_TOPLAM_OLUM_VAKA
(
TARIH  date
)
AS
BEGIN
(
    SELECT CONTINENTNAME, SUM(MAX(TOTAL_CASES)), SUM(MAX(TOTAL_DEATHS))   FROM CONTINENT CO 
    INNER JOIN COUNTRY COU            ON COU.CONTINENTID=CO.ID 
    INNER JOIN CASES_BY_COUNTRIES CBC ON CBC.COUNTRY_ID=CO.ID
    WHERE CONTINENTNAME='Asia'
    GROUP BY CO.CONTINENTNAME, TOTAL_CASES, TOTAL_DEATHS;
    )
END;


EXECUTE TARIHE_GORE_TOPLAM_OLUM_VAKA @TARIH ''