--Verilen tarihte kýtalardaki yoðun bakýmda yatan hasta sayýsýnýn prosedürünü 

CREATE OR REPLACE PROCEDURE TARIHE_GORE_KITADAKI_YOGUNBAKIM
@TARIH date
AS 
BEGIN
SELECT CO.ID, CONTINENTNAME,SUM (ICU_PATIENTS) AS TOTAL_ICU_PATIENTS FROM CONTINENT CO 
INNER JOIN COUNTRY COU            ON COU.CONTINENTID=CO.ID 
INNER JOIN CASES_BY_COUNTRIES CBC ON CBC.COUNTRY_ID=COU.COUNTRYID
WHERE CONTINENTNAME 'AVRUPA' OR 'NORTH AMERICA'
GROUP BY CONTINENTNAME, CO.ID
ORDER BY CO.ID
END;



EXEC @TARIH' ' 