--EN SON TARÝHTE MÝLYON  BAÞINA MÝN VE MAX TEST VE CASES YENÝ VAKA ORANLARININ VÝEWI
CREATE VIEW NEW_TEST
AS
SELECT COUNTRYNAME, 
MIN(NEW_CASES_PER_MILLION) AS NEW_CASES_PER_MILLION , 
MAX(NEW_TESTS_PER_THOUSAND) AS NEW_TESTS_PER_THOUSAND
FROM CASES_BY_COUNTRIES CBC
INNER JOIN COUNTRY COU ON COU.COUNTRYID=CBC.COUNTRY_ID
WHERE 1=1
AND DATE_='06.01.2021'
GROUP BY COUNTRYNAME