--aylýk nüfüs yoðunluðuna göre, aralýk ayý  yüksek vaka alan ülkeleri ve bu ülkelerin kýtalarýný bulunuz.
CREATE VIEW VW_MAX_CASES
AS
SELECT  DISTINCT CBC.COUNTRY_ID, COUNTRYNAME,CBC.POPULATION_ , MAX(NEW_CASES)
FROM CASES_BY_COUNTRIES CBC 
INNER JOIN COUNTRY COU ON COU.COUNTRYID=CBC.COUNTRY_ID
INNER JOIN CONTINENT CONT ON CONT.ID=COU.CONTINENTID
WHERE DATE_ BETWEEN '01.12.2020' AND '31/12/2020'