CREATE TABLE COVID.CONTINENT(
ID INTEGER NOT NULL,
CONTINENTNAME NVARCHAR2(100),

CONSTRAINT PK_CONTINENT PRIMARY KEY(ID)
);

CREATE TABLE COUNTRY(
COUNTRYID INTEGER NOT NULL,
CONTINENTID INTEGER,
COUNTRYCODE NVARCHAR2(50),
COUNTRYNAME NVARCHAR2(100),


CONSTRAINT PK_COUNTRY PRIMARY KEY(COUNTRYID),
CONSTRAINT FK_CONTINENT_COUNTRY FOREIGN KEY (CONTINENTID) REFERENCES CONTINENT(ID)
);


CREATE TABLE STATE_(
ID INTEGER,
COUNTRYID INTEGER,
STATECODE NVARCHAR2(2),
STATENAME NVARCHAR2(100),
AREA NVARCHAR2(100),
POPULATION  NVARCHAR2(50),
CAPITAL NVARCHAR2(50),


CONSTRAINT PK_STATE PRIMARY KEY(ID),
CONSTRAINT FK_STATE FOREIGN KEY(COUNTRYID) REFERENCES COUNTRY(COUNTRYID)
);



CREATE TABLE STATECASES1(
STATECASESID INTEGER NOT NULL PRIMARY KEY,
DATE_ DATE,
STATECODE NVARCHAR2(2),
POSITIVE_ INTEGER,
NEGATIVE INTEGER,
TOTALRESULTS INTEGER,
HOSPITILIZED_CURRENTLY INTEGER,
INICU_CURRENTLY INTEGER,
ONVENTILATOR_CUMULATIVE INTEGER,
RECOVERED INTEGER,
DATAQUALITYGRADE NVARCHAR2(3),
LASTUPDATEDET DATE,
CHECKTIMEET DATE,
DEATH INTEGER, 
HOSPITALIZED INTEGER,
TOTALTESTVIRAL INTEGER,
NEGATIVETESTSVIRAL INTEGER,
POSITIVETESTSVIRAL INTEGER,
POSITIVECASEVIRAL INTEGER,
DEATHCONFIRMED INTEGER,
DEATHINCREASE INTEGER,
HOSPITALIZEDINCREASE INTEGER,
HASH_ NVARCHAR2(200)
--CONSTRAINT PK_CASESID  PRIMARY KEY(STATECASESID),
--CONSTRAINT FK_CASES_STATE FOREIGN KEY(STATECODE) REFERENCES STATE_(STATECODE)
);